# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ca325b8701772aa6079b69eaa493e919b644da8dad482a3e6f53c5091c9018abe59f076416c6f7dbd671b0022bbb756069b63d3d24f4e4c3f9ca2c353574ad9

test:
  secret_key_base: cbff3b260ea7cbe1e67d57b3282fb407aace0c35c41f15c2e207dafc7883f136655322621ad79c1afca11ca9bbcd7d5cefdaafbbb778aa0399e96fb03aa5adda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
